### ISSUE TITLE
color by conversation score

### ISSUE THREAD

**Issue by uuwuyi** [ncbi/SSDraw#1]
Hi, it's a very cool tool. Can you please explain a bit more on the color related to the conversation e.g. does yellow suggest low conversation in that position? Many thanks!

**Comment by ethanchen1301** [comment]
Hi, I'm glad you like the program! The default colormap used by SSDraw is inferno, where lighter colors like yellow indicate a higher score. You can specify another colormap from matplotlib's library using the --color_map option.

[https://matplotlib.org/stable/tutorials/colors/colormaps.html](url)
