### ISSUE TITLE
Not able to run the notebook: list index out of range

### ISSUE THREAD

**Issue by AleksandraPanfilova** [ncbi/SSDraw#2]
Hello! I have an issue with Colab Notebook version. I am submitting these fasta and pdb files:
[example.zip](https://github.com/ethanchen1301/SSDraw/files/12658337/example.zip)

And get an error:
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-26-cc31ba5aa98f>](https://localhost:8080/#) in <cell line: 145>()
    143 
    144 
--> 145 SSDraw(args)

2 frames
[<ipython-input-16-38217c931c00>](https://localhost:8080/#) in SS_align(alignment, ID, seq, ss, i_start, i_end)
    331 
    332     # check if the dssp annotation has any extra residues not in the alignment
--> 333     if a[0][1] != a_seq:
    334         print("extra residues in pdb found\n")
    335 

IndexError: list index out of range`

I am not sure where this comes from, from the look at the code I assume it can happen if aligment 'a' is empty, but I don't see why. If I remove first aa from fasta, it gives out the same error.

**Comment by ethanchen1301** [comment]
Hello, thank you for reaching out! Could you try changing the name argument to be either "WT" or "Dihydrofolate reductase" in the Define Variables cell? The way the code is written now, the name argument has to include something from the fasta file description line for the program to know which sequence to read.

**Comment by AleksandraPanfilova** [comment]
This worked, thank you!
