### ISSUE TITLE
how to deal with gaps in alignment file

### ISSUE THREAD

**Issue by Yogesh1-11** [ncbi/SSDraw#4]
hi thankyou for SSDRAW
i was using it but i felt a few gaps that needs to be filled.
1. SSDRAW uses sequence from MSA to plot, that comes with long gappy regions too troublesome. switching to a3m format from fasta will be better i guess.
2. residue numbers should be there at the beginning and end of every secondary structure. or  a scheme of numbering marking every 25-50 residues can be used. thank you once again. these gaps are needed to be fixed for practical usage of ssdraw

**Comment by ethanchen1301** [comment]
Hi Yogesh,

Thanks for your suggestion to include a3m format as input. We will consider adding that as a future feature. One of the limitations of using sequences from an MSA is that if the sequence alignment is very gappy, the resulting image will not look great. Possible ways to improve this would be to generate a new MSA with less gaps, or to give SSDraw a single ungapped sequence as the input fasta file. Another thing you could try is cropping out the long gap regions by using the --start and --end options (see Example 2 in the README for an example).

As to your second point, we do provide the option to number the residues in the image with the --ticks option. For example, "--ticks 5" would label every 5th residue. There is an option to add ticks in the colab notebook version as well.

Thanks, and let me know if you have any more questions/suggestions.

Ethan
